# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c0208cf4c7b387441f3db4bfb5fd5a9b2d8465918c66ebee323f0725206e4cdad71ca2527550c0a2d2db07208103f2b19199600594f6efbb5db393ea3851dd49

test:
  secret_key_base: 50ca085e82a6adb7abdfb4f72af7e240ab78c83d6336378c187724a3b8554b285c4dced7e231df864630a251e05a70f7a40d73c59e0cd18f005ff7d1ea69fd70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
